export class AppConstants {
  static readonly DEFAULT_STATUS_HEIGHT: number = 56;
  static readonly DEFAULT_NAV_HEIGHT: number = 48;
  static readonly BUNDLE_NAME: string = 'com.hyx.clock'
}

export class Icons {
  static readonly FONT_FAMILY: string = 'iconfont'
  static readonly FAMILY_SRC: ResourceStr = $rawfile('iconfont.ttf')

  static readonly SETTINGS: string = '\ue785'
  static readonly THEME_DARK: string = '\ue634'
  static readonly THEME_LIGHT: string = '\ue600'
  static readonly ARROW_RIGHT: string = '\ue63c'
  static readonly EMAIL: string = '\ue68a'
  static readonly FEEDBACK: string = '\ue6fa'
  static readonly PRIVACY: string = '\ue612'
  static readonly PACK_UP: string = '\ue64d'
  static readonly TIPS: string = '\ue7a3'
  static readonly COMMENTS: string = '\ue8b9'
  static readonly CUSTOM: string = '\ue62f'
  static readonly ABOUT: string = '\ue607'
  static readonly CLOCK: string = '\ue74f'
  static readonly FLIP: string = '\ue69d'
}