export class AppConstants {
  static DEFAULT_STATUS_HEIGHT: number = 0;
  static DEFAULT_NAV_HEIGHT: number = 0;
  static readonly BUNDLE_NAME: string = 'com.hyx.clock'
}

export class Icons {
  static readonly FONT_FAMILY: string = AppConstants.BUNDLE_NAME + 'iconfont'
  static readonly FAMILY_SRC: ResourceStr = $rawfile('iconfont.ttf')

  static readonly FLIP_NUM_FONT_FAMILY: string = 'flip-num-font'
  static readonly DIGITAL_NUM_FONT_FAMILY: string = 'digital-num-font'
  static readonly DIGITAL_NUM1_FONT_FAMILY: string = 'digital-num-font1'

  static readonly FLIP_NUM_FONT_FAMILY_SRC: ResourceStr = $rawfile('flip-num-font.ttf')
  static readonly DIGITAL_NUM_FONT_FAMILY_SRC: ResourceStr = $rawfile('digital-num-font.ttf')
  static readonly DIGITAL_NUM1_FONT_FAMILY_SRC: ResourceStr = $rawfile('digital-num-font1.ttf')

  static readonly FONT_ERBOS_DRACO_1ST_OPEN_NBP: string = 'font-erbos-draco-1st-open-nbp'
  static readonly FONT_JURA: string = 'font-jura'
  static readonly FONT_ICELAND: string = 'font-iceland'
  static readonly FONT_RALEWAY_DOTS: string = 'font-raleway-dots'
  static readonly FONT_NOVA_SQUARE: string = 'font-nova-square'
  static readonly FONT_NOVA_MONO: string = 'font-nova-mono'
  static readonly FONT_GEO: string = 'font-geo'
  static readonly FONT_MEGRIM: string = 'font-megrim'
  static readonly FONT_MONOFETT: string = 'font-monofett'
  static readonly FONT_ORBITRON: string = 'font-orbitron'
  static readonly FONT_EXO2: string = 'font-exo2'
  static readonly FONT_AUDIOWIDE: string = 'font-audiowide'
  static readonly FONT_DSEG7_CLASSIC: string = 'font-dseg7-classic'
  static readonly FONT_IBM_PLEX_MONO: string = 'font-ibm-plex-mono'
  static readonly FONT_SPACE_MONO: string = 'font-space-mono'

  static readonly FONT_ERBOS_DRACO_1ST_OPEN_NBP_SRC: ResourceStr = $rawfile('fonts/erbos_draco_1st_open_nbp.ttf')
  static readonly FONT_JURA_SRC: ResourceStr = $rawfile('fonts/jura_regular.ttf')
  static readonly FONT_ICELAND_SRC: ResourceStr = $rawfile('fonts/iceland_regular.ttf')
  static readonly FONT_RALEWAY_DOTS_SRC: ResourceStr = $rawfile('fonts/raleway_dots_regular.ttf')
  static readonly FONT_NOVA_SQUARE_SRC: ResourceStr = $rawfile('fonts/nova_square_regular.ttf')
  static readonly FONT_NOVA_MONO_SRC: ResourceStr = $rawfile('fonts/nova_mono_regular.ttf')
  static readonly FONT_GEO_SRC: ResourceStr = $rawfile('fonts/geo_regular.ttf')
  static readonly FONT_MEGRIM_SRC: ResourceStr = $rawfile('fonts/megrim_regular.ttf')
  static readonly FONT_MONOFETT_SRC: ResourceStr = $rawfile('fonts/monofett_regular.ttf')
  static readonly FONT_ORBITRON_SRC: ResourceStr = $rawfile('fonts/orbitron_wght.ttf')
  static readonly FONT_EXO2_SRC: ResourceStr = $rawfile('fonts/exo2_wght.ttf')
  static readonly FONT_AUDIOWIDE_SRC: ResourceStr = $rawfile('fonts/audiowide_regular.ttf')
  static readonly FONT_DSEG7_CLASSIC_SRC: ResourceStr = $rawfile('fonts/dseg7_classic_regular.ttf')
  static readonly FONT_IBM_PLEX_MONO_SRC: ResourceStr = $rawfile('fonts/ibm_plex_mono_regular.ttf')
  static readonly FONT_SPACE_MONO_SRC: ResourceStr = $rawfile('fonts/space_mono_regular.ttf')

  static readonly SETTINGS: string = '\ue785'
  static readonly THEME_DARK: string = '\ue634'
  static readonly THEME_LIGHT: string = '\ue600'
  static readonly ARROW_RIGHT: string = '\ue63c'
  static readonly EMAIL: string = '\ue68a'
  static readonly FEEDBACK: string = '\ue6fa'
  static readonly PRIVACY: string = '\ue612'
  static readonly PACK_UP: string = '\ue64d'
  static readonly TIPS: string = '\ue7a3'
  static readonly COMMENTS: string = '\ue8b9'
  static readonly CUSTOM: string = '\ue62f'
  static readonly ABOUT: string = '\ue607'
  static readonly CLOCK: string = '\ue74f'
  static readonly FLIP: string = '\ue69d'
  static readonly SCREEN_ORIENTATION: string = '\ue624'
  static readonly THEME_STROKE_ICON: string = '\ue65e'
  static readonly THEME_FILL_ICON: string = '\ue860'
  static readonly CHECKED: string = '\ue61d'
  static readonly BACK: string = '\ue62e'
  static readonly MINI_WINDOW: string = '\ue621'
  static readonly SHARE: string = '\ue8b0'
  static readonly CHECK_UPDATE: string = '\ue823'
  static readonly USER_AGREEMENT: string = '\ue702'
  static readonly CLOSE: string = '\ue613'
  static readonly ADD: string = '\ue62a'
  static readonly DELETE: string = '\ue627'
}
